+v2k
-sverilog
-timescale=1ns/1ps
+incdir+.
+incdir+PPU
+incdir+Streaming_RMSNorm_Unit
+incdir+PPU_RMSNorm_Fusion
+incdir+systolic_array/src
+incdir+softmax_FPGA_package/softmax_FPGA_package

ViT_DDR_AxiLite_Wrapper.sv
ViT_System_Core.sv
ViT_InputLoadFSM.sv
ViT_Image_Accelerator_Top.sv
Patch_Embedding_Systolic_Top.sv
ViT_Accelerator_Top.sv
Global_Controller_FSM.sv
Streaming_RMSNorm_Unit/Streaming_RMSNorm_Unit.sv
Streaming_RMSNorm_Unit/Streaming_RMSNorm_RowPacker.sv
Streaming_RMSNorm_Unit/RMSNorm_Fusion_ROMs_Case_All.sv
PPU/PPU.sv
PPU/Requant_Unit.sv
PPU/GELU_Unit.sv
PPU/Residual_Add_Unit.sv
PPU/PPU_Residual_RMS_Tail.sv
PPU/RMS_Stat_Accumulator.sv
PPU_RMSNorm_Fusion/Gamma_Buffer_BRAM.sv
PPU_RMSNorm_Fusion/Token_Stat_BRAM.sv
systolic_array/src/Systolic.v
systolic_array/src/ActivationMem.v
systolic_array/src/WeightMem.v
systolic_array/src/BiasMem.v
softmax_FPGA_package/softmax_FPGA_package/Softmax_Unit.sv
sim/tb_vit_fulldesign_compile.sv
